package easylink.service;

import java.util.Date;

import easylink.dto.AlarmLevel;
import easylink.entity.Alarm;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

import easylink.repository.AlarmRepository;
import easylink.repository.DeviceRepository;

@Service
public class AlarmService {
	
	@Autowired
	AlarmRepository alarmRepo;
	
	@Autowired
    DeviceRepository deviceRepo;
	
	public Page<Alarm> findAlarm(Integer deviceId, String type, AlarmLevel level,
                                 Date startTime, Date endTime, int pageNumber, int pageSize) {
		String deviceToken = null;
		if (deviceId != null)
			deviceToken = deviceRepo.findById(deviceId).get().getDeviceToken();
		return alarmRepo.findAlarm(deviceToken, type, level, startTime, endTime, PageRequest.of(pageNumber-1, pageSize));
	}
	
	public Page<Alarm> findAll(int pageNumber, int pageSize) {
		return alarmRepo.findAll(PageRequest.of(pageNumber-1, pageSize));
	}
	
	// Save alarm generated by rule
	// TODO:  create queue to save alarm in batch
	public void saveAlarm(Alarm a) {
		alarmRepo.save(a);
	}
}
